import React from "react";
import ReactDOM from "react-dom";
import App from './src/app/App';
// import 'zone.js/dist/zone';
// import 'zone.js/dist/long-stack-trace-zone';
// import 'zone.js/dist/proxy';
// import 'zone.js/dist/sync-test';
// import 'zone.js/dist/jasmine-patch';
// import 'zone.js/dist/async-test';
// import 'zone.js/dist/fake-async-test';
ReactDOM.render(<App text=""/>, document.getElementById('root'));